/** Display names for live bot bets (mirrors frontend player pool). */
export const PLAYER_NAMES = [
  "Lethabo_M", "ThaboK", "Sipho99", "NomvulaZ", "lucky_strike", "KelesoG",
  "BonganiX", "ZaneleD", "MikeT_ZA", "AyandaN", "TebogoW", "FatimahR",
  "highroller88", "NhlanhlaB", "SibusoS", "Gugu_plays", "RefilweMO", "DikelediP",
  "MahlatseMN", "ProPlayerZA", "Mpho_T", "LindiweMC", "TshepoNR", "AceGambler",
  "KaraboFF", "PreciousNK", "big_win_sa", "SelloMK", "NomceboTZ", "ThulisileP",
  "DevilDarts", "KhumoB", "YusufRA", "crash_king", "MasegoNO", "TebelloKK",
  "ZithuleleM", "BalungileN", "Oratile_D", "NoxoloBT", "JabulaniSP", "MokoenaRC",
  "moonshot99", "PumzaMB", "SifoPD", "BuhleNZ", "TlotloGS", "NkululekoM",
  "AluphiweTA", "rocketman_za", "MamelloKR", "SinenhlaNB", "OlwethuDZ", "LungisaEM",
  "NtsikiPB", "KhanyisoTL", "GcinileMH", "MthunziKS", "ZandisDG", "ThabisileNP",
  "Vuyo_M", "Lerato_J", "SaneleP", "Nandi_K", "xFlyHighx", "ThembaR",
  "ZolaBee", "KagisoW", "NeoPilot", "AmahleT", "Rivaldo7", "BusisiweN",
  "PilotAce", "LwaziM", "Onalerona", "StevoZA", "mul_tip_ly", "HlumeloD",
  "KatlegoB", "NtokozoF", "SkyRunner", "PhumzileK", "CashOutPro", "WandileS",
  "Boitumelo", "MarcusVdM", "LeboMaps", "TurboBet", "Samkelo87", "NalediR",
  "JetStream", "AndileNx", "QueenBets", "SifisoL", "GoldRushZA", "PalesaM",
  "DylanCPT", "MandlaK", "aviator_fan", "Rethabile", "Kamohelo", "BladeRunner",
  "ZinhleZ", "TumiBets", "NicoPretoria", "Sphelele", "LuckyCharm", "AsandaG",
  "KairoX", "MelusiN", "BetsyBee", "ThandoQ", "multiplier_x", "SenzoM",
  "NompiloH", "FlyBoySA", "ChadJHB", "ZeeCash", "Rorisang", "MusaDlamini",
  "TakeoffTom", "BabalwaN", "KgotsoP", "NightOwlBet", "YangaS", "PortiaW",
  "DuncanFly", "Sbongile", "MaxMultiplier", "LuyandaC", "VIP_Player", "HannahBets",
  "Siyabonga", "NeoMabaso", "CloudNine", "RethaK", "BaneleT", "StormRider",
  "NolwaziM", "GarethW", "PhilaBets", "ZamaniX", "LeratoFly", "MziBets",
  "KabeloR", "TanakaM", "WingMan88", "NomsaD", "Altitude", "VusiPilot",
  "JackpotJoe", "Smangele", "TurboCash", "EthanBets", "Nokuthula", "RedBaronZA",
  "PilotLight", "MbaliS", "SiyaKhumalo", "DoubleUp", "AneleM", "FortuneFly",
  "GontseB", "RuanV", "SkyKing", "NtombiL", "CashPilot", "LiamZA",
  "BongiweT", "AceOfSkies", "MandisaP", "Propeller", "Tshegofatso", "FlySafely",
  "Obakeng", "NadiaBets", "HighRoller_", "SboneloM", "ZenithX", "ThabisoN",
] as const;
